# Generated by Django 3.2.5 on 2021-07-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.CharField(max_length=200)),
                ('reading', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='WaterPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water.waterreadings')),
            ],
        ),
    ]
